[package]
name = "{{name}}"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Daniel Gregoire <daniel.l.gregoire@gmail.com>"]

[lib]
name="{{lib-name}}"
path="src/lib.rs"

[[bin]]
name="{{bin-name}}"
path="src/main.rs"

[dependencies]
clap = "~2.26"
